<a href="https://colab.research.google.com/github/kkimyunjoo/24-1-ESAA/blob/main/0315_grouping%EF%BC%BFoccupation%EF%BC%BFExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [4]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [5]:
users = pd.read_table('/content/drive/MyDrive/Colab Notebooks/24-1 ESAA/u.user2.txt', sep='|')

In [6]:
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. Discover what is the mean age per occupation

In [7]:
users.groupby('occupation').age.mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [25]:
users['is_male'] = users['gender'].apply(lambda x: True if x == 'M' else False)
users['is_male']

0       True
1      False
2       True
3       True
4      False
       ...
938    False
939     True
940     True
941    False
942     True
Name: is_male, Length: 943, dtype: bool

In [23]:
(users.groupby('occupation').is_male.sum() / users.groupby('occupation').gender.count()).sort_values(ascending = False)

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [12]:
print(users.groupby('occupation').age.min())

occupation
administrator    21
artist           19
doctor           28
educator         23
engineer         22
entertainment    15
executive        22
healthcare       22
homemaker        20
lawyer           21
librarian        23
marketing        24
none             11
other            13
programmer       20
retired          51
salesman         18
scientist        23
student           7
technician       21
writer           18
Name: age, dtype: int64

In [13]:
print(users.groupby('occupation').age.max())

occupation
administrator    70
artist           48
doctor           64
educator         63
engineer         70
entertainment    50
executive        69
healthcare       62
homemaker        50
lawyer           53
librarian        69
marketing        55
none             55
other            64
programmer       63
retired          73
salesman         66
scientist        55
student          42
technician       55
writer           60
Name: age, dtype: int64

In [14]:
users.groupby('occupation').age.agg(['min', 'max'])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [15]:
users.groupby(['occupation', 'gender']).age.mean()

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [26]:
# Step 5ì™€ ìœ ì‚¬
users['is_male'] = users['gender'].apply(lambda x: True if x == 'M' else False)
users['is_female'] = users['gender'].apply(lambda x: True if x == 'F' else False)
users.groupby(by='occupation')[['is_male','is_female']].mean()

                is_male  is_female
occupation
administrator  0.544304   0.455696
artist         0.535714   0.464286
doctor         1.000000   0.000000
educator       0.726316   0.273684
engineer       0.970149   0.029851
entertainment  0.888889   0.111111
executive      0.906250   0.093750
healthcare     0.312500   0.687500
homemaker      0.142857   0.857143
lawyer         0.833333   0.166667
librarian      0.431373   0.568627
marketing      0.615385   0.384615
none           0.555556   0.444444
other          0.657143   0.342857
programmer     0.909091   0.090909
retired        0.928571   0.071429
salesman       0.750000   0.250000
scientist      0.903226   0.096774
student        0.693878   0.306122
technician     0.962963   0.037037
writer         0.577778   0.422222